### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by kellyselden** [thefrontside/ember-impagination#119]
Can you release https://github.com/thefrontside/ember-impagination/pull/105 to clean up console chatter?

**Comment by Robdel12** [comment]
This was probably cleaned up in one of the alpha releases (& probably #120)

**Comment by kellyselden** [comment]
While it would be nice to get a stable patch, we will try out the alpha release and see if we have any issues. Thanks.

**Comment by cowboyd** [comment]
There are some API changes. The biggest is that it has been "de-magicked". It will not attempt to set the read offset for you. You'll have to do that yourself. This makes it more strictly DDAU since side effects will never be triggered simply by reading the dataset state.

The downside is that you need to explicitly trigger side-effects inside of an action. Curious how your experience goes, and please let us know of any feedback!
