### ISSUE TITLE
Semver violation

### ISSUE THREAD

**Issue by TopsyCM** [thefrontside/ember-impagination#172]
It looks like the changes from the 1.0.0-alpha.x releases have gotten rolled into a 0.2.1 release. However, there are breaking changes in the way impagination needs to be implemented since 0.2.0. I think even the way the underlying impagination library is included has changed. In short, bumping from 0.2.0 to 0.2.1 in my project fails completely. Can you please revert this and make the new release at least 0.3?

**Comment by flexyford** [comment]
Thanks @TopsyCM 

We were not able to revert the v0.2.1 release since it was [released more than 24 hours ago](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy), but have [deprecated v0.2.1](https://github.com/thefrontside/ember-impagination/releases/tag/0.2.2) in favor of v0.2.2 which is equivalent to v0.2.0

**Comment by flexyford** [comment]
New major released finally [released as v1.0.0-alpha.6](https://github.com/thefrontside/ember-impagination/releases/tag/1.0.0-alpha.6)
